development:
  adapter: postgresql
  database: devfacotry_cloud_analytics
  username: postgres
  password: password

test:
  adapter: postgresql
  database: devfacotry_cloud_analytics_test
  username: postgres
  password: password